# Base configs
baseurl: "https://tariqphotography.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tariq"
subtitle: "See the world through my eyes!"
author: "Tariq"
header:
 title: "Photography"
 subtitle: "by Tariq"
footer:
 name: "Hey there, my name is Tariq"
 bio: "I am a blah blah guy doing blah blah stuff and specialized in photography."
web_design: "GK"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
